version: '3.7'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_challenge
    restart: on-failure:5
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgresql

  postgresql:
    build:
      context: .
      dockerfile: ./compose/local/db/Dockerfile
    image: postgres:14
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data: